A-Congre-bility/Acongrebility/Acongrebility/Models/Congressmembers.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Acongrebility.Models
{
    public class CongressmemberPartyViewModel
    {
        public List<Congressmembers> Congressmembers { get; set; }
        public SelectList Parties { get; set; }
        public string Party { get; set; }
        public string SearchString { get; set; }
    }
    public class Congressmembers
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateTookOffice { get; set; }
        public string Role { get; set; }
        public string Pic { get; set; }
        public string Party { get; set; }
        public string VotingHistory { get; set; }

    }
}

A-Congre-bility/Acongrebility/Acongrebility/Controllers/CongressmembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Acongrebility.Data;
using Acongrebility.Models;

namespace Acongrebility.Controllers
{
    public class CongressmembersController : Controller
    {
        private readonly AcongrebilityContext _context;

        public CongressmembersController(AcongrebilityContext context)
        {
            _context = context;
        }

        // GET: Congressmembers
        public async Task<IActionResult> Index(string searchString, string congressmemberParty)
        {
            IQueryable<string> partyQuery = from c in _context.Congressmembers
                                            orderby c.Party
                                            select c.Party;

            var congressmembers = from c in _context.Congressmembers
                                  select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                congressmembers = congressmembers.Where(s => s.Name.Contains(searchString));
            }

            return View(await congressmembers.ToListAsync());
        }

        // GET: Congressmembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congressmembers = await _context.Congressmembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (congressmembers == null)
            {
                return NotFound();
            }

            return View(congressmembers);
        }

        // GET: Congressmembers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Congressmembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DateTookOffice,Role,Pic,Party,VotingHistory")] Congressmembers congressmembers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(congressmembers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(congressmembers);
        }

        // GET: Congressmembers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congressmembers = await _context.Congressmembers.FindAsync(id);
            if (congressmembers == null)
            {
                return NotFound();
            }
            return View(congressmembers);
        }

        // POST: Congressmembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DateTookOffice,Role,Pic,Party,VotingHistory")] Congressmembers congressmembers)
        {
            if (id != congressmembers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(congressmembers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CongressmembersExists(congressmembers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(congressmembers);
        }

        // GET: Congressmembers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var congressmembers = await _context.Congressmembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (congressmembers == null)
            {
                return NotFound();
            }

            return View(congressmembers);
        }

        // POST: Congressmembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var congressmembers = await _context.Congressmembers.FindAsync(id);
            _context.Congressmembers.Remove(congressmembers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CongressmembersExists(int id)
        {
            return _context.Congressmembers.Any(e => e.Id == id);
        }
    }
}

A-Congre-bility/Acongrebility/Acongrebility/Views/Congressmembers/Create.cshtml
@model Acongrebility.Models.Congressmembers

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Congressmembers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTookOffice" class="control-label"></label>
                <input asp-for="DateTookOffice" class="form-control" />
                <span asp-validation-for="DateTookOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pic" class="control-label"></label>
                <input asp-for="Pic" class="form-control" />
                <span asp-validation-for="Pic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Party" class="control-label"></label>
                <input asp-for="Party" class="form-control" />
                <span asp-validation-for="Party" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VotingHistory" class="control-label"></label>
                <input asp-for="VotingHistory" class="form-control" />
                <span asp-validation-for="VotingHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

A-Congre-bility/Acongrebility/Acongrebility/Views/Congressmembers/Delete.cshtml
@model Acongrebility.Models.Congressmembers

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Congressmembers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTookOffice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTookOffice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Party)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Party)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VotingHistory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VotingHistory)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

A-Congre-bility/Acongrebility/Acongrebility/Views/Congressmembers/Details.cshtml
@model Acongrebility.Models.Congressmembers

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Congressmembers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTookOffice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTookOffice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Party)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Party)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VotingHistory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VotingHistory)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

A-Congre-bility/Acongrebility/Acongrebility/Views/Congressmembers/Edit.cshtml
@model Acongrebility.Models.Congressmembers

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Congressmembers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTookOffice" class="control-label"></label>
                <input asp-for="DateTookOffice" class="form-control" />
                <span asp-validation-for="DateTookOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pic" class="control-label"></label>
                <input asp-for="Pic" class="form-control" />
                <span asp-validation-for="Pic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Party" class="control-label"></label>
                <input asp-for="Party" class="form-control" />
                <span asp-validation-for="Party" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VotingHistory" class="control-label"></label>
                <input asp-for="VotingHistory" class="form-control" />
                <span asp-validation-for="VotingHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

A-Congre-bility/Acongrebility/Acongrebility/Views/Congressmembers/Index.cshtml
@model Acongrebility.Models.CongressmemberPartyViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Congressmembers" asp-action="Index" method="get">
    <p>
        <select asp-for="Party" asp-items="Model.Parties">
            <option value="">All</option>
        </select>

        Name: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].DateTookOffice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].Role)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].Pic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].Party)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Congressmembers[0].VotingHistory)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Congressmembers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTookOffice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Party)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VotingHistory)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>